// Screens from code (docs/JOURNEYS.md §3, CONTRACTS.md §23.4): the detector per
// framework convention, id / name derivation, the product.json merge rules, the
// write paths (`ruah app scan`, systems) and the bank-app fixture end to end.
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { describe, expect, test } from "vitest";
import { emptyProduct, type ProductFile, type Screen, validateProduct } from "../src/contracts/product.js";
import { mergeScannedScreens, namespaceScreens, planScannedProduct, writeScannedProduct } from "../src/product/screens-merge.js";
import { scanRepoWithScreens, scanScreens } from "../src/scan/index.js";
import { MAX_SCREENS } from "../src/scan/detectors/screens.js";
import { rebuildSystem } from "../src/system/manage.js";
import { main } from "../src/cli.js";

const BANK = join(import.meta.dirname, "fixtures", "bank-app");

function tmp(prefix = "ruah-screens-"): string {
  return realpathSync(mkdtempSync(join(tmpdir(), prefix)));
}

/** A throwaway repo from { relPath: content }; objects are written as JSON. */
function repo(files: Record<string, string | object>): string {
  const root = tmp();
  for (const [rel, content] of Object.entries(files)) {
    const abs = join(root, rel);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, typeof content === "string" ? content : JSON.stringify(content, null, 2));
  }
  return root;
}

const pkg = (deps: Record<string, string>, name = "app"): object => ({ name, private: true, dependencies: deps, devDependencies: { vite: "^6.0.0" } });

const screensOf = (root: string): Screen[] => scanScreens(root, { useGit: false });
const routes = (screens: Screen[]): string[] => screens.map((s) => s.route ?? "");
const byRoute = (screens: Screen[], route: string): Screen => {
  const s = screens.find((x) => x.route === route);
  if (s === undefined) throw new Error(`no screen for ${route}: ${routes(screens).join(", ")}`);
  return s;
};

describe("detector: framework conventions", () => {
  test("Next.js app router: groups dropped, params, slots / private / intercepting / api skipped, metadata title", () => {
    const root = repo({
      "package.json": pkg({ next: "^15.0.0", react: "^19.0.0" }),
      "app/layout.tsx": "export default function L({ children }) { return children; }",
      "app/page.tsx": "export default function Page() { return null; }",
      "app/(marketing)/about/page.tsx": 'export const metadata = { title: "About us" };\nexport default function About() { return null; }',
      "app/accounts/[id]/page.tsx": "export default function A() { return null; }",
      "app/docs/[...slug]/page.mdx": "# Docs",
      "app/shop/[[...slug]]/page.tsx": "export default function S() { return null; }",
      "app/@modal/login/page.tsx": "export default function M() { return null; }",
      "app/_components/x/page.tsx": "export default function P() { return null; }",
      "app/photos/(.)[id]/page.tsx": "export default function I() { return null; }",
      "app/api/health/route.ts": "export function GET() {}",
      "app/api/debug/page.tsx": "export default function D() { return null; }",
    });
    const screens = screensOf(root);
    expect(routes(screens)).toEqual(["/", "/about", "/accounts/:id", "/docs/*slug", "/shop/*slug?"]);
    expect(byRoute(screens, "/about")).toEqual({
      id: "about",
      name: "About us",
      route: "/about",
      path: "app/(marketing)/about/page.tsx",
      node: "app",
      source: "scan",
    });
    expect(byRoute(screens, "/")).toMatchObject({ id: "home", name: "Home", path: "app/page.tsx" });
    expect(byRoute(screens, "/accounts/:id")).toMatchObject({ id: "accounts-id", name: "Accounts / :id" });
  });

  test("Next.js pages router (also under src/): _app / _document / _error / api skipped, index → parent", () => {
    const root = repo({
      "package.json": pkg({ next: "^14.0.0" }),
      "src/pages/_app.tsx": "",
      "src/pages/_document.tsx": "",
      "src/pages/_error.tsx": "",
      "src/pages/api/hello.ts": "",
      "src/pages/index.tsx": "export default function Index() { return null; }",
      "src/pages/blog/[slug].tsx": "",
      "src/pages/settings/index.jsx": "<title>Settings</title>",
    });
    const screens = screensOf(root);
    expect(routes(screens)).toEqual(["/", "/blog/:slug", "/settings"]);
    expect(byRoute(screens, "/settings")).toMatchObject({ id: "settings", name: "Settings", path: "src/pages/settings/index.jsx" });
  });

  test("TanStack Router: routeTree.gen.ts routes and their files", () => {
    const gen = `/* eslint-disable */
// This file was automatically generated by TanStack Router.
import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as AuthRouteImport } from './routes/_auth'

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/posts': typeof PostsRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts': typeof PostsIndexRoute
  '': typeof AuthRouteWithChildren
}
`;
    const root = repo({
      "package.json": pkg({ "@tanstack/react-router": "^1.0.0", react: "^19.0.0" }),
      "src/routeTree.gen.ts": gen,
      "src/routes/__root.tsx": "",
      "src/routes/index.tsx": "",
      "src/routes/about.tsx": "",
      "src/routes/posts.tsx": "<Outlet />",
      "src/routes/posts.index.tsx": "",
      "src/routes/posts.$postId.tsx": "",
      "src/routes/_auth.tsx": "",
    });
    const screens = screensOf(root);
    expect(screens.map((s) => [s.route, s.path])).toEqual([
      ["/", "src/routes/index.tsx"],
      ["/about", "src/routes/about.tsx"],
      ["/posts", "src/routes/posts.index.tsx"],
      ["/posts/:postId", "src/routes/posts.$postId.tsx"],
    ]);
    expect(byRoute(screens, "/posts/:postId").id).toBe("posts-postid");
  });

  test("TanStack Router file routes (no routeTree.gen.ts): $params, pathless _layouts, index, route.tsx, ignored -files", () => {
    const root = repo({
      "package.json": pkg({ "@tanstack/react-router": "^1.0.0", react: "^19.0.0" }),
      "src/routes/__root.tsx": "",
      "src/routes/index.tsx": "",
      "src/routes/about.lazy.tsx": "",
      "src/routes/posts.tsx": "export const Route = createFileRoute('/posts')({ component: () => <Outlet /> })",
      "src/routes/posts.$postId.tsx": "",
      "src/routes/_auth.tsx": "",
      "src/routes/_auth/login.tsx": "",
      "src/routes/settings/route.tsx": "",
      "src/routes/settings/index.tsx": "",
      "src/routes/files/$.tsx": "",
      "src/routes/-components/card.tsx": "",
      "src/routes/posts_.$postId.edit.tsx": "",
    });
    const screens = screensOf(root);
    expect(screens.map((s) => [s.route, s.path])).toEqual([
      ["/", "src/routes/index.tsx"],
      ["/about", "src/routes/about.lazy.tsx"],
      ["/files/*", "src/routes/files/$.tsx"],
      ["/login", "src/routes/_auth/login.tsx"],
      ["/posts/:postId", "src/routes/posts.$postId.tsx"],
      ["/posts/:postId/edit", "src/routes/posts_.$postId.edit.tsx"],
      ["/settings", "src/routes/settings/index.tsx"],
    ]);
  });

  test("React Router: <Route> JSX nesting, index routes, layouts, redirects and catch-alls", () => {
    const root = repo({
      "package.json": pkg({ react: "^19.0.0", "react-router-dom": "^7.0.0" }),
      "src/App.tsx": `import { Routes, Route, Navigate } from "react-router-dom";
import Layout from "./Layout";
import { Home } from "./pages/Home";
import User from "./pages/User";
// <Route path="/commented-out" element={<Home />} />
export function App() {
  return (
    <Routes>
      <Route path="/" element={<Layout />}>
        <Route index element={<Home />} />
        <Route path="users/:id" element={<User user={{ name: "x" }} />} />
        <Route path="settings">
          <Route path="profile" Component={Profile} />
        </Route>
        <Route path="*" element={<NotFound />} />
      </Route>
      <Route path="/old" element={<Navigate to="/" replace />} />
    </Routes>
  );
}
`,
      "src/Layout.tsx": "",
      "src/pages/Home.tsx": "export function Home() { return null; }",
      "src/pages/User.tsx": "export default function User() { return null; }",
    });
    const screens = screensOf(root);
    expect(screens.map((s) => [s.route, s.path])).toEqual([
      ["/", "src/pages/Home.tsx"],
      ["/settings/profile", "src/App.tsx"],
      ["/users/:id", "src/pages/User.tsx"],
    ]);
  });

  test("React Router: RouteObject[] config with children, index, Component and lazy imports", () => {
    const root = repo({
      "package.json": pkg({ react: "^19.0.0", "react-router": "^7.0.0" }),
      "src/router.ts": `import type { RouteObject } from "react-router";
import { Root } from "@/root";
export const routes: RouteObject[] = [
  {
    path: "/",
    Component: Root,
    children: [
      { index: true, lazy: () => import("./pages/dashboard") },
      { path: "reports/:year", lazy: () => import("./pages/reports") },
    ],
  },
  { path: "/login", Component: Root },
];
`,
      "src/root.tsx": "export function Root() { return null; }",
      "src/pages/dashboard.tsx": "",
      "src/pages/reports/index.tsx": "",
    });
    const screens = screensOf(root);
    expect(screens.map((s) => [s.route, s.path])).toEqual([
      ["/", "src/pages/dashboard.tsx"],
      ["/login", "src/root.tsx"],
      ["/reports/:year", "src/pages/reports/index.tsx"],
    ]);
  });

  test("Remix flat routes: _index, $params, pathless layouts, folder routes, resource routes skipped, meta title", () => {
    const root = repo({
      "package.json": pkg({ "@remix-run/react": "^2.0.0", "@remix-run/node": "^2.0.0", react: "^18.0.0" }),
      "app/root.tsx": "export default function App() { return <Outlet />; }",
      "app/routes/_index.tsx": "export default function Index() { return null; }",
      "app/routes/accounts.$id.tsx": 'export const meta = () => [{ title: "Account" }];\nexport default function A() { return null; }',
      "app/routes/_auth.tsx": "export default function AuthLayout() { return <Outlet />; }",
      "app/routes/_auth.login.tsx": "export default function Login() { return null; }",
      "app/routes/api.health.ts": "export const loader = () => new Response('ok');",
      "app/routes/settings/route.tsx": "export default function Settings() { return null; }",
      "app/routes/settings/form.tsx": "export default function Form() { return null; }",
      "app/routes/transfer.tsx": "export default function T() { return <Outlet />; }",
      "app/routes/transfer.new.tsx": "export default function N() { return null; }",
    });
    const screens = screensOf(root);
    expect(screens.map((s) => [s.route, s.path])).toEqual([
      ["/", "app/routes/_index.tsx"],
      ["/accounts/:id", "app/routes/accounts.$id.tsx"],
      ["/login", "app/routes/_auth.login.tsx"],
      ["/settings", "app/routes/settings/route.tsx"],
      ["/transfer/new", "app/routes/transfer.new.tsx"],
    ]);
    expect(byRoute(screens, "/accounts/:id").name).toBe("Account");
  });

  test("React Router 7 framework: app/routes.ts index / route / layout / prefix", () => {
    const root = repo({
      "package.json": pkg({ "@react-router/dev": "^7.0.0", "react-router": "^7.0.0", react: "^19.0.0" }),
      "app/routes.ts": `import { type RouteConfig, index, layout, prefix, route } from "@react-router/dev/routes";
export default [
  index("routes/home.tsx"),
  route("about", "routes/about.tsx"),
  layout("routes/auth/layout.tsx", [route("login", "routes/auth/login.tsx")]),
  ...prefix("concerts", [index("routes/concerts/home.tsx"), route(":city", "routes/concerts/city.tsx")]),
] satisfies RouteConfig;
`,
      "app/routes/home.tsx": "",
      "app/routes/about.tsx": "",
      "app/routes/auth/layout.tsx": "",
      "app/routes/auth/login.tsx": "",
      "app/routes/concerts/home.tsx": "",
      "app/routes/concerts/city.tsx": "",
    });
    expect(screensOf(root).map((s) => [s.route, s.path])).toEqual([
      ["/", "app/routes/home.tsx"],
      ["/about", "app/routes/about.tsx"],
      ["/concerts", "app/routes/concerts/home.tsx"],
      ["/concerts/:city", "app/routes/concerts/city.tsx"],
      ["/login", "app/routes/auth/login.tsx"],
    ]);
  });

  test("Expo Router: (tabs) groups dropped, _layout / +not-found / +html / +api skipped", () => {
    const root = repo({
      "package.json": pkg({ expo: "^52.0.0", "expo-router": "^4.0.0", "react-native": "^0.76.0" }),
      "app/_layout.tsx": "",
      "app/(tabs)/_layout.tsx": "",
      "app/(tabs)/index.tsx": "",
      "app/(tabs)/settings.tsx": "",
      "app/user/[id].tsx": "",
      "app/+not-found.tsx": "",
      "app/+html.tsx": "",
      "app/api/hello+api.ts": "",
    });
    expect(screensOf(root).map((s) => [s.route, s.path])).toEqual([
      ["/", "app/(tabs)/index.tsx"],
      ["/settings", "app/(tabs)/settings.tsx"],
      ["/user/:id", "app/user/[id].tsx"],
    ]);
  });

  test("SvelteKit: +page.svelte, groups, [param] and [param=matcher]", () => {
    const root = repo({
      "package.json": pkg({ "@sveltejs/kit": "^2.0.0", svelte: "^5.0.0" }),
      "src/routes/+page.svelte": "",
      "src/routes/+layout.svelte": "",
      "src/routes/(app)/dashboard/+page.svelte": "<svelte:head><title>Dashboard</title></svelte:head>",
      "src/routes/blog/[slug]/+page.svelte": "",
      "src/routes/items/[id=integer]/+page.svelte": "",
      "src/routes/api/+server.ts": "",
    });
    const screens = screensOf(root);
    expect(routes(screens)).toEqual(["/", "/blog/:slug", "/dashboard", "/items/:id"]);
    expect(byRoute(screens, "/dashboard").name).toBe("Dashboard");
  });

  test("Nuxt: pages/**/*.vue, [id], catch-all, parent pages with <NuxtPage> skipped", () => {
    const root = repo({
      "package.json": pkg({ nuxt: "^3.0.0", vue: "^3.0.0" }),
      "pages/index.vue": "<template><div /></template>",
      "pages/users.vue": "<template><NuxtPage /></template>",
      "pages/users/[id].vue": "<script setup>useHead({ title: 'User' })</script>",
      "pages/[...slug].vue": "",
    });
    const screens = screensOf(root);
    expect(routes(screens)).toEqual(["/", "/*slug", "/users/:id"]);
    expect(byRoute(screens, "/users/:id")).toMatchObject({ id: "users-id", name: "User" });
  });

  test("only frontend packages: a server with a pages/ folder has no screens", () => {
    const root = repo({
      "package.json": { name: "api", dependencies: { express: "^5.0.0", next: "^15.0.0" } },
      "app/page.tsx": "",
    });
    expect(screensOf(root)).toEqual([]);
  });
});

describe("detector: ids and names", () => {
  test('"/" is home unless /home exists; slugs, dedupe, names from routes and components', () => {
    const root = repo({
      "package.json": pkg({ next: "^15.0.0" }),
      "app/page.tsx": "export default function WelcomePage() { return null; }",
      "pages/home.tsx": "", // pages router beside the app router
      "app/transfer/new/page.tsx": "",
      "app/a-b/page.tsx": "",
      "app/a/b/page.tsx": "",
      "app/my_account/page.tsx": "",
    });
    const screens = screensOf(root);
    expect(screens.map((s) => [s.route, s.id, s.name])).toEqual([
      ["/", "welcome", "Welcome"],
      ["/a-b", "a-b", "A b"],
      ["/a/b", "a-b-2", "A / b"],
      ["/home", "home", "Home"],
      ["/my_account", "my_account", "My account"],
      ["/transfer/new", "transfer-new", "Transfer / new"],
    ]);
    for (const s of screens) expect(s.id).toMatch(/^[a-z0-9][a-z0-9._-]{0,63}$/);
  });

  test("two frontend packages with screens: ids prefixed with the package's node id", () => {
    const root = repo({
      "pnpm-workspace.yaml": "packages:\n  - apps/*\n",
      "package.json": { name: "mono", private: true },
      "apps/web/package.json": pkg({ next: "^15.0.0" }, "@acme/web"),
      "apps/web/app/page.tsx": "",
      "apps/admin/package.json": pkg({ next: "^15.0.0" }, "@acme/admin"),
      "apps/admin/app/page.tsx": "",
      "apps/admin/app/users/page.tsx": "",
    });
    const screens = screensOf(root);
    expect(screens.map((s) => [s.id, s.route, s.node, s.path])).toEqual([
      ["admin.home", "/", "admin", "apps/admin/app/page.tsx"],
      ["web.home", "/", "web", "apps/web/app/page.tsx"],
      ["admin.users", "/users", "admin", "apps/admin/app/users/page.tsx"],
    ]);
    // Node ids are the map's own element ids.
    const { architecture } = scanRepoWithScreens(root, { useGit: false });
    for (const s of screens) expect(architecture.nodes.some((n) => n.id === s.node && n.type === "frontend")).toBe(true);
  });

  test(`capped at ${MAX_SCREENS} screens per repo, deterministic order`, () => {
    const files: Record<string, string | object> = { "package.json": pkg({ next: "^15.0.0" }) };
    for (let i = 0; i < MAX_SCREENS + 50; i++) files[`app/p${String(i).padStart(3, "0")}/page.tsx`] = "";
    const screens = screensOf(repo(files));
    expect(screens).toHaveLength(MAX_SCREENS);
    expect(screens[0]?.route).toBe("/p000");
    expect(new Set(screens.map((s) => s.id)).size).toBe(MAX_SCREENS);
  });
});

// ---------------------------------------------------------------- merge rules

const scan = (id: string, route: string, extra: Partial<Screen> = {}): Screen => ({
  id,
  name: id,
  route,
  path: `web/src/routes${route}.tsx`,
  node: "web",
  source: "scan",
  ...extra,
});

function withJourney(product: ProductFile, screen: string): ProductFile {
  return {
    ...product,
    personas: [{ id: "retail", name: "Retail customer" }],
    journeys: [{ id: "pay-rent", name: "Pay rent", persona: "retail", goal: "Pay my rent", steps: [{ id: "s1", screen, action: "Opens it" }] }],
  };
}

describe("merge (§3.2)", () => {
  test("no file and no screens: nothing; first screens: a new file with empty personas / journeys", () => {
    expect(mergeScannedScreens(null, [])).toEqual({ product: null, warnings: [] });
    const { product, warnings } = mergeScannedScreens(null, [scan("home", "/home")]);
    expect(warnings).toEqual([]);
    expect(product).toEqual({ version: 1, personas: [], screens: [scan("home", "/home")], journeys: [] });
  });

  test("scan screens are replaced; user / agent screens and journeys are untouched", () => {
    const existing: ProductFile = withJourney(
      {
        ...emptyProduct(),
        screens: [
          { id: "checkout", name: "Checkout", route: "/checkout", source: "user" },
          { id: "idea", name: "Idea", source: "agent" },
          scan("home", "/home", { name: "Old name" }),
          scan("old", "/old"),
        ],
      },
      "checkout",
    );
    const { product, warnings } = mergeScannedScreens(existing, [scan("home", "/home"), scan("cards", "/cards")]);
    expect(warnings).toEqual([]);
    expect(product?.screens.map((s) => [s.id, s.source, s.name])).toEqual([
      ["checkout", "user", "Checkout"],
      ["idea", "agent", "Idea"],
      ["cards", "scan", "cards"],
      ["home", "scan", "home"],
    ]);
    expect(product?.journeys).toEqual(existing.journeys);
    expect(product?.personas).toEqual(existing.personas);
    expect(validateProduct(product).ok).toBe(true);
  });

  test("a referenced scanned screen that vanished stays, with a warning; unreferenced ones go", () => {
    const existing = withJourney({ ...emptyProduct(), screens: [scan("cards", "/cards"), scan("loans", "/loans"), scan("home", "/home")] }, "cards");
    const { product, warnings } = mergeScannedScreens(existing, [scan("home", "/home")]);
    expect(warnings).toEqual(["screen /cards no longer found in web"]);
    expect(product?.screens.map((s) => s.id)).toEqual(["cards", "home"]);
    expect(product?.screens[0]).toEqual(scan("cards", "/cards"));
    expect(validateProduct(product).ok).toBe(true);
  });

  test("a rescan keeps the id and shot of the screen at the same node + route; id clashes get a suffix", () => {
    const existing: ProductFile = withJourney(
      {
        ...emptyProduct(),
        screens: [
          { id: "home", name: "Home (hand-made)", source: "user" },
          scan("dashboard", "/", { shot: "dashboard.png" }),
        ],
      },
      "dashboard",
    );
    // The detector now calls "/" "home" (taken by the user's screen) and finds /home too.
    const { product, warnings } = mergeScannedScreens(existing, [scan("home", "/"), scan("home-2", "/home")]);
    expect(warnings).toEqual([]);
    expect(product?.screens.map((s) => [s.id, s.route, s.shot])).toEqual([
      ["home", undefined, undefined],
      ["dashboard", "/", "dashboard.png"],
      ["home-2", "/home", undefined],
    ]);
    // A user screen that claims a route replaces the scanned one.
    const claimed = mergeScannedScreens(
      { ...emptyProduct(), screens: [{ id: "my-cards", name: "Cards", route: "/cards", node: "web", source: "user" }] },
      [scan("cards", "/cards")],
    );
    expect(claimed.product?.screens.map((s) => s.id)).toEqual(["my-cards"]);
    expect(validateProduct(product).ok).toBe(true);
  });

  test("system namespacing: ids and nodes <repoId>:…, paths <repoId>/…", () => {
    expect(namespaceScreens("web", [scan("home", "/home")])).toEqual([
      { ...scan("home", "/home"), id: "web:home", node: "web:web", path: "web/web/src/routes/home.tsx" },
    ]);
  });
});

describe("writing product.json", () => {
  test("created on the first screens, rewritten only on change, never over an invalid file", () => {
    const dir = tmp();
    const file = join(dir, "product.json");
    expect(writeScannedProduct(file, [])).toMatchObject({ written: false, screens: 0 });
    expect(existsSync(file)).toBe(false);

    expect(writeScannedProduct(file, [scan("home", "/home")])).toMatchObject({ written: true, screens: 1 });
    const first = statSync(file).mtimeMs;
    expect(planScannedProduct(file, [scan("home", "/home")]).unchanged).toBe(true);
    expect(writeScannedProduct(file, [scan("home", "/home")]).written).toBe(false);
    expect(statSync(file).mtimeMs).toBe(first);

    writeFileSync(file, '{ "version": 1, "personas": [], "screens": [], "journeys": [{ "id": "x" }] }');
    const bad = writeScannedProduct(file, [scan("home", "/home")]);
    expect(bad.written).toBe(false);
    expect(bad.warnings[0]).toMatch(/is invalid .*screens not updated/);
    expect(readFileSync(file, "utf8")).toContain('"id": "x"');
  });
});

// ---------------------------------------------------------------- fixture end to end

const BANK_SCREENS: Screen[] = [
  { id: "welcome", name: "Welcome", route: "/", path: "web/src/routes/welcome.tsx", node: "web", source: "scan" },
  { id: "cards", name: "Cards", route: "/cards", path: "web/src/routes/cards.tsx", node: "web", source: "scan" },
  { id: "home", name: "Home", route: "/home", path: "web/src/routes/home.tsx", node: "web", source: "scan" },
  { id: "transfer-id-done", name: "Transfer / :id / done", route: "/transfer/:id/done", path: "web/src/routes/transfer/done.tsx", node: "web", source: "scan" },
  { id: "transfer-new", name: "Transfer / new", route: "/transfer/new", path: "web/src/routes/transfer/new.tsx", node: "web", source: "scan" },
];

async function quietMain(argv: string[]): Promise<{ code: number; err: string }> {
  const write = process.stderr.write.bind(process.stderr);
  const lines: string[] = [];
  process.stderr.write = ((chunk: string | Uint8Array): boolean => {
    lines.push(String(chunk));
    return true;
  }) as typeof process.stderr.write;
  try {
    return { code: await main(argv), err: lines.join("") };
  } finally {
    process.stderr.write = write;
  }
}

describe("bank-app fixture", () => {
  test("scan: web (React Router) screens with routes, files and node; api and ledger-db on the map", () => {
    const { architecture, screens } = scanRepoWithScreens(BANK, { useGit: false });
    expect(screens).toEqual(BANK_SCREENS);
    const node = (id: string) => architecture.nodes.find((n) => n.id === id);
    expect(node("web")?.type).toBe("frontend");
    expect(node("api")?.type).toBe("service");
    expect(node("ledger-db")?.type).toBe("datastore");
    expect(scanScreens(BANK, { useGit: false })).toEqual(screens);
  });

  test("`ruah app scan` writes product.json; a re-scan keeps a referenced screen that vanished, with a warning", async () => {
    const root = tmp();
    cpSync(BANK, root, { recursive: true });
    const first = await quietMain(["scan", root]);
    expect(first.code).toBe(0);
    expect(first.err).toMatch(/5 screens/);
    const file = join(root, "product.json");
    const product = JSON.parse(readFileSync(file, "utf8")) as ProductFile;
    expect(product).toEqual({ version: 1, personas: [], screens: BANK_SCREENS, journeys: [] });

    // A journey through /cards, then /cards leaves the router.
    writeFileSync(file, JSON.stringify(withJourney(product, "cards"), null, 2));
    const main = join(root, "web/src/main.tsx");
    writeFileSync(main, readFileSync(main, "utf8").replace('  { path: "/cards", element: <Cards /> },\n', ""));
    const again = await quietMain(["scan", root]);
    expect(again.code).toBe(0);
    expect(again.err).toContain("warning: screen /cards no longer found in web");
    const next = JSON.parse(readFileSync(file, "utf8")) as ProductFile;
    expect(next.screens).toEqual(BANK_SCREENS);
    expect(next.journeys).toHaveLength(1);
    expect(validateProduct(next, { root }).ok).toBe(true);

    // Unreferenced: dropped on the next scan.
    writeFileSync(file, JSON.stringify({ ...next, journeys: [], personas: [] }, null, 2));
    await quietMain(["scan", root]);
    expect((JSON.parse(readFileSync(file, "utf8")) as ProductFile).screens.map((s) => s.id)).toEqual(
      BANK_SCREENS.filter((s) => s.id !== "cards").map((s) => s.id),
    );
  });

  test("system: each repo's screens in the system's product.json, namespaced like the map", () => {
    const dir = tmp();
    cpSync(BANK, join(dir, "bank"), { recursive: true });
    mkdirSync(join(dir, "platform"));
    writeFileSync(
      join(dir, "platform", "ruah.system.json"),
      JSON.stringify({ version: 1, name: "bank", repos: [{ id: "web", path: "../bank/web" }, { id: "api", path: "../bank/api" }] }),
    );
    const result = rebuildSystem(join(dir, "platform"), { version: "test" });
    const product = JSON.parse(readFileSync(join(dir, "platform", "product.json"), "utf8")) as ProductFile;
    expect(product.screens).toEqual(result.screens);
    const home = product.screens.find((s) => s.route === "/home");
    expect(home).toEqual({ id: "web:home", name: "Home", route: "/home", path: "web/src/routes/home.tsx", node: "web:bank-web", source: "scan" });
    expect(result.architecture.nodes.some((n) => n.id === home?.node)).toBe(true);
    expect(product.screens).toHaveLength(5);
    expect(validateProduct(product).ok).toBe(true);
  });
});
